### ISSUE TITLE
"Failed to Fetch" when running test.

### ISSUE THREAD

**Issue by pme123** [bpmn-io/dmn-testing-plugin#17] opened 2020-11-03 19:27 UTC
__Describe the Bug__

When hitting the Test Button I get the following Message:

![image](https://user-images.githubusercontent.com/3437927/98030882-f7774c00-1e11-11eb-9366-f41789462266.png)

__Steps to Reproduce__

1. downloaded the sources as zip
2. copied it in /Users/mpa/Library/Application Support/camunda-modeler/resources/plugins
3. opened Camunda Modeler
4. Opened DMN.
5. DMN Testing.
6. Hit Test Button

__Expected Behavior__

Test runs as shown in the Anim GIF.

__Environment__

- Camunda Modeler 4.3.0
- OS: MAC Catalina

**Comment by pme123** [comment] 2020-11-03 20:08
After running `npm install` it started to work.

**Comment by barmac** [comment] 2020-11-04 07:43
This is a duplicate of https://github.com/bpmn-io/dmn-testing-plugin/issues/15

**Closed as completed by barmac** 2020-11-04 07:43 UTC
Labels: bug

**Comment by pme123** [comment] 2020-11-04 07:48
This information is missing in the 'How to use' section of the README.

**Comment by barmac** [comment] 2020-11-04 07:53
Indeed, for now we can use it as a quick fix.

**Comment by naveinn** [comment] 2024-06-13 16:49
I am facing the same issue, I followed the above steps, I can see that my server it not starting, I event had console.log statements to ensure if the control comes to main.js app as i start the application but it doesn't seem to get executed at all, my client is working well though ... am i missing anything here?

the server is exepcted to start as soon as i start the camunda modeler right?

To add on I am using camunda - 8 (cloud) here

**Comment by barmac** [comment] 2024-06-14 07:30
Hi,

This plugin was developed with Camunda 7 in mind only. If you want to provide a migration PR as in https://github.com/bpmn-io/dmn-testing-plugin/issues/22#issuecomment-2166717457, please let's discuss the problems in the PR.
